version: '3.5'
services:
  users:
    build: './'
    ports:
      - '3004:3004'
    networks:
      - ms_network
    deploy:
        resources:
            limits:
              cpus: 0.25
              memory: 500M
networks:
  ms_network:
    driver: bridge
    name: ms_network
